server:
  port: 7070
  
  
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: SPRING
    password: SPRING
    hikari:
      auto-commit: true
      
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


